spring.application.name=gatekeeper
spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration,org.springframework.cloud.client.discovery.simple.reactive.SimpleReactiveDiscoveryClientAutoConfiguration,org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration
logging.level.com.kabutar.gatekeeper.filter=DEBUG
logging.level.com.kabutar.gatekeeper.ratelimiter.algorithm=DEBUG
